spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    url: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}}?authSource=admin
    user: ${spring.data.mongodb.username}
    password: ${spring.data.mongodb.password}
    enabled: true

  config:
    import: optional:file:../.env[.properties]

crypto:
  card-secret-key: ${CARD_SECRET_KEY}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  endpoints:
    web:
      exposure:
        include: health,info
