server:
  port: ${PAYMENT_SERVICE_PORT}

spring:
  data:
    mongodb:
      host: ${PAYMENT_SERVICE_MONGO_DB_HOST}
      port: ${PAYMENT_SERVICE_MONGO_DB_PORT}
      database: ${PAYMENT_SERVICE_MONGO_DB_NAME}
      username: ${PAYMENT_SERVICE_MONGO_DB_USERNAME}
      password: ${PAYMENT_SERVICE_MONGO_DB_PASSWORD}
      authentication-database: admin

  config:
    activate:
      on-profile: local

app:
  fake-bank-url: ${EXTERNAL_BANK_HOST}:${EXTERNAL_BANK_PORT}
